# config file for automatic testing at travis-ci.org
language: python

python:
	- "3.5"
	- "3.4"
	- "3.3"

install:
	- pip install --editable .
	- pip install coveralls

script:
	# command to run tests and collect test coverage
	- coverage run --source flask_url_for_helpers setup.py test

after_success: coveralls
